#!/usr/bin/awk -f

##################################################################
BEGIN {
    FS = "\t"
}

##################################################################
tolower($2) == "neutral" {
    if ($NF ~ /EmoExpression::[^:]+::Polarity=positive/ \
	&& $NF !~ /EmoExpression::[^:]+::Polarity=negative/)
	$2 = "positive"
    else if ($NF ~ /EmoExpression::[^:]+::Polarity=negative/ \
	&& $NF !~ /EmoExpression::[^:]+::Polarity=positive/)
	$2 = "negative"

    print
    next
}

1
